travis:
  secure:
    BINSTAR_TOKEN: v+Lg8uq9AttxwbCNvC/oCZX/omHp0TfcrIYnEk6jHSnZFVYOChTcrS891SwWRcwrSk+pMKS9rMjxq21bP2GIF0QfKxgjiM2GuGbEddvb64qNK/ZK3Tx0/6jAaRwAM6Q9HJdpc4Zlb6oKCwOULoAGfCwqjyFuZYDvvJY+6cAmmuvYDTg6HBLyKNVcsDGxrzwQSQmYVqHmSfaURcf2IEGQJJlNtQNyyzLqJRJh4wyI4wJY1vtKJDqg2/PF5WFGVX0Awo/wpVnC/aNF65kpthPr8kyWkX5V8bqQhDETm3GUezW+bWGPe+wmGx+C91dtFdejR18uLHKBIIEriiVGgkRNXVMD69q5aStA65WDy803pnaw25BroOtmxKqmD79QNh/dryBMYcWig/JuMihfg/Ua3Py96rnGub3zeq1PvSHVdOlx115FHBm73K0EezU4N91Fg7yPdml8o2bCdv0/8LHffKL5DuUMeuEkKoxHzXmzkOvbMYKVsU3L1b1aWonyadHFoAhM4Qk+8FFldh2iL8s6+rN7SgacDCgZVs08g7KdBwxgZUWX0W3ICtxRNAi3CB+OGfxpVP9MoJMKYAIoOnYW/QBZ9UBA6gvqIed6V85i7u9KhpIUqQA2nxF6SJuBHXfWG+6eSTSpZRpKs/4e57ciVeyXC5A0rUiuTne1L96Cc9A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
  osx: circle
